apiVersion: v1
kind: PersistentVolume
metadata:
  name: netdata-parent-k8s-state
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  hostPath:
        path: /var/cache/netdata