---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 2 
  selector:
    matchLabels:
     app: cassandra
  template:
    spec:
      nodeSelector:
        sfi2-uc1: cassandra
        type: cassandra
    metadata:
      labels:
        type: cassandra
        #sfi2-uc1: cassandra
        app: cassandra
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: sfi2-uc1
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            sfi2-uc1: cassandra    
      containers:
        - name: cassandra
          image: cassandra:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Cassandra"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          volumeMounts:
            - name: cassandra-storage
              mountPath: /var/lib/cassandra/data
      volumes:
        - name: cassandra-storage
          persistentVolumeClaim:
            claimName: cassandra-storage
