apiVersion: v1
kind: Pod
metadata:
   name: loadgen
spec:
   containers:
   - name: loadgen
     image: moreirar/loadgen:latest
     command: ['sh', '-c', 'echo The app is running! && sleep 3600000']
     imagePullPolicy: IfNotPresent
     ports:
     - containerPort: 6379
   terminationGracePeriodSeconds: 60
