apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: cassandra
    type: local
    sfi2-uc1: cassandra
  name: cassandra-storage
  namespace: sfi2-uc1
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
